batch_size: 64
num_workers: 4

model: ResNet50
model_kwargs:
    num_classes: 200

counterfactuals_kwargs:
    apply_soft_constraint: False
    lambd: 0.0
    temperature: None
    model: class_prediction_model_cub_res50/best_model.ckpt
    max_num_distractors: 1
